{% set version = '1.4.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rsyncrosim
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://github.com/syncrosim/rsyncrosim/releases/download/{{ version }}/rsyncrosim_{{ version }}.tar.gz
    - https://github.com/syncrosim/rsyncrosim/archive/v{{ version }}.tar.gz
  sha256: 772a13772a4ab311606465fd56df50317626d0d3e1c33f696e4b26b10a498639

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]

  host:
    - r-base
    - r-dbi
    - r-rsqlite
    - r-gtools
    - r-lifecycle
    - r-raster

  run:
    - r-base
    - r-dbi
    - r-rsqlite
    - r-gtools
    - r-lifecycle
    - r-raster

test:
  commands:
    - $R -e "library('rsyncrosim')"           # [not win]
    - "\"%R%\" -e \"library('rsyncrosim')\""  # [win]

about:
  home: <https://syncrosim.github.io/rsyncrosim/>

  license: MIT
  summary: '''SyncroSim'' is a generalized framework for managing scenario-based datasets (<https://syncrosim.com/>).
    ''rsyncrosim'' provides an interface to ''SyncroSim''. Simulation models can be
    added to ''SyncroSim'' in order to transform these datasets, taking advantage of
    general features such as defining scenarios of model inputs, running Monte Carlo
    simulations, and summarizing model outputs. ''rsyncrosim'' requires ''SyncroSim''
    2.3.5 or higher (API documentation: <https://docs.syncrosim.com/>).'

  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - katieb1

# Package: rsyncrosim
# Type: Package
# Title: The R Interface to 'SyncroSim'
# Version: 1.4.1
# Authors@R: c( person("Colin", "Daniel", email = "colin.daniel@apexrms.com", role = c("aut", "cre")), person("Josie", "Hughes", email = "josie.hughes@canada.ca", role = "aut"), person("Valentin", "Lucet", role = "aut"), person("Alex", "Embrey", role = "aut"), person("Katie", "Birchard", role = "aut"), person("Leonardo", "Frid", role = "aut"), person("Tabitha", "Kennedy", role = "aut"), person("ApexRMS", role="cph"))
# Description: 'SyncroSim' is a generalized framework for managing scenario-based datasets (<https://syncrosim.com/>). 'rsyncrosim' provides an interface to 'SyncroSim'. Simulation models can be added to 'SyncroSim' in order to transform these datasets, taking advantage of general features such as defining scenarios of model inputs, running Monte Carlo simulations, and summarizing model outputs. 'rsyncrosim' requires 'SyncroSim' 2.3.5 or higher (API documentation: <https://docs.syncrosim.com/>).
# License: MIT + file LICENSE
# Encoding: UTF-8
# Imports: methods, DBI, RSQLite, raster, gtools, lifecycle
# Suggests: knitr, testthat, ggplot2, Rcpp, rgdal, rmarkdown, covr
# SystemRequirements: SyncroSim (>=2.3.5)
# Collate: 'AAAClassDefinitions.R' 'addPackage.R' 'addRow.R' 'addon.R' 'autogentags.R' 'backup.R' 'breakpoint.R' 'command.R' 'datasheet.R' 'datasheetRaster.R' 'dateModified.R' 'delete.R' 'dependency.R' 'deprecated.R' 'description.R' 'disableAddon.R' 'enableAddon.R' 'filepath.R' 'ignoreDependencies.R' 'info.R' 'internalHelpers.R' 'name.R' 'scenarioId.R' 'projectId.R' 'sqlStatement.R' 'scenario.R' 'project.R' 'ssimLibrary.R' 'session.R' 'internalWrappers.R' 'mergeDependencies.R' 'owner.R' 'package.R' 'parentId.R' 'print.R' 'printCmd.R' 'readOnly.R' 'removePackage.R' 'rsyncrosim.R' 'run.R' 'runLog.R' 'saveDatasheet.R' 'silent.R' 'ssimEnvironment.R' 'ssimUpdate.R' 'updatePackage.R' 'version.R'
# RoxygenNote: 7.1.1
# URL: <https://syncrosim.github.io/rsyncrosim/>
# BugReports: https://github.com/syncrosim/rsyncrosim/issues/
# NeedsCompilation: no
# Packaged: 2021-10-27 20:12:24 UTC; birch
# Author: Colin Daniel [aut, cre], Josie Hughes [aut], Valentin Lucet [aut], Alex Embrey [aut], Katie Birchard [aut], Leonardo Frid [aut], Tabitha Kennedy [aut], ApexRMS [cph]
# Maintainer: Colin Daniel <colin.daniel@apexrms.com>
# Repository: CRAN
# Date/Publication: 2021-10-27 22:00:02 UTC
